version: "3.8"

services:
  frontend:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    container_name: innovatech_frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always
  # Base de Datos Centralizada (MySQL)
  db-innovatech:
    image: mysql:8.0
    container_name: db-mysql-citt
    restart: always
    environment:
      - MYSQL_DATABASE=bd_despachos
      - MYSQL_ROOT_PASSWORD=tupassword
      - MYSQL_USER=Despacho1
      - MYSQL_PASSWORD=tupassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - innovatech-net

  # Microservicio de Ventas (Desde Docker Hub)
  venta-back:
    image: nico22222/venta-back:latest # <--- Cambiado
    container_name: venta-back
    depends_on:
      - db-innovatech
    ports:
      - "8080:8080"
    environment:
      - DB_ENDPOINT=db-innovatech
      - DB_PORT=3306
      - DB_NAME=bd_despachos
      - DB_USERNAME=Despacho1
      - DB_PASSWORD=tupassword
    volumes:
      - ventas-logs:/app/logs
    networks:
      - innovatech-net
    restart: always

  # Microservicio de Despachos (Desde Docker Hub)
  despacho-back:
    image: nico22222/despacho-back:latest # <--- Cambiado
    container_name: despacho-back
    depends_on:
      - db-innovatech
    ports:
      - "8081:8081"
    environment:
      - DB_ENDPOINT=db-innovatech
      - DB_PORT=3306
      - DB_NAME=bd_despachos
      - DB_USERNAME=Despacho1
      - DB_PASSWORD=tupassword
    volumes:
      - despachos-logs:/app/logs
    networks:
      - innovatech-net
    restart: always

volumes:
  mysql-data:
  ventas-logs:
  despachos-logs:

networks:
  innovatech-net:
    driver: bridge
